version: "3.9"

services:
  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node-exporter
    network_mode: host
    pid: host
    command:
      - '--path.rootfs=/host'
      - '--collector.systemd'
    volumes:
      - "/:/host:ro,rslave"
      - "/run/systemd/system:/run/systemd/system:ro"
      - "/var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket:ro"

  prometheus:
    image: docker.io/prom/prometheus:latest
    container_name: prometheus
    network_mode: host
    volumes:
      - /home/ec2-user/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:Z
      - /home/ec2-user/monitoring/nginx-alert.yml:/etc/prometheus/nginx-alert.yml:Z

  alertmanager:
    image: quay.io/prometheus/alertmanager:latest
    container_name: alertmanager
    network_mode: host
