---
- hosts: localhost 
  collections:
  - netapp.ontap
  vars_files:
  - vars.yaml 
  tasks:
  - name: "Create LIFs"
    netapp.ontap.na_ontap_interface:
      state: present
      interface_name: nfs-data
      home_port: e0a
      home_node: ontap-select-node
      admin_status: up
      failover_scope: home_node_only
      is_auto_revert: true
      interface_type: ip
      address: 10.9.92.34
      netmask: 255.255.255.0
      vserver: test
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: false
