---
- hosts: localhost
  collections:
  - netapp.ontap
  vars_files:
  - vars.yaml
  tasks:
  - name: "Create StorageVM"
    na_ontap_svm:
      state: present
      name: test
      services:
        nfs:
          allowed: true
          enabled: true
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: false
