---
- hosts: localhost
  collections:
  - netapp.ontap
  vars_files:
  - vars.yaml
  tasks:
  - name: "Create volume"
    netapp.ontap.na_ontap_volume:
      state: present
      name: test
      aggregate_name: ontap_select_node_VM_DISK_1
      vserver: shareStorage
      size: 1
      size_unit: gb
      policy: default
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: false
