---
- hosts: linux
  remote_user: azureuser
  tasks:
  - name: "Check telnet disabled"
    ansible.builtin.service:
      name: kdump
      state: present
      enabled: yes
    become: true
    become_user: root
