---
- hosts: linux
  remote_user: azureuser
  tasks:
  - name: "Check telnet disabled"
    ansible.builtin.service:
      name: telnet
      state: stopped
      enabled: no
    become: true
    become_user: root
