---
- name: "Start DR Application"
  hosts: drwin
  vars:
    iis_ip: 10.9.92.24
    code_path: C:\\apps\\postgresql-dotnet-core\\PostgreSqlDotnetCore
    iis_site_path: C:\\sites\\demo
  tasks:
  - name: "Install Chocolatey"
    win_chocolatey:
      name:
      - chocolatey
      - chocolatey-core.extension
      state: present

  - name: "Install IIS"
    win_feature:
      name: "web-server"
      state: present
      restart: yes
      include_sub_features: yes
      include_management_tool: yes

  - name: "Install packages"
    win_chocolatey:
      name: "{{ item.name }}"
      version: "{{ item.version }}"
      state: present
    loop:
    - { name: 'git', version: '2.42.0' }
    - { name: 'dotnet-sdk', version: '7.0.400' }
    - { name: 'dotnet-aspnetcoremodule-v2', version: '17.0.23196' }

  - name: "Publish application"
    win_shell: "dotnet publish --output {{ iis_site_path }}\\app /p:EnvironmentName=Production"
    args:
      chdir: "{{ code_path }}"

  - name: "Start IIS"
    win_iis_website:
      name: demo
      state: started
      port: 80
      ip: "{{ iis_ip }}"
      physical_path: "{{ iis_site_path }}\\app"
      application_pool: SampleAppPool