---
- name: Monitor configuration
  hosts: all
  sources:
  - name: webhook
    ansible.eda.webhook:
      host: 0.0.0.0
      port: 5000
  rules:
  - name: Configuration Changed
    condition: event.payload.message != ""
    action:
      run_job_template:
        name: Recover
        organization: Default
